services:
  postgres:
    container_name: postgres-node-do-zero
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data/
