POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o video 01",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/id
Content-Type: application/json

{
  "title": "Video Teste",
  "description": "Esse é o video 01s",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/id
